# Generated by Django 2.2 on 2019-04-26 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_auto_20190426_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Owner_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round1_date', models.DateField()),
                ('round2_date', models.DateField()),
                ('round3_date', models.DateField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='form_app.player')),
                ('player10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player10', to='form_app.player')),
                ('player11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player11', to='form_app.player')),
                ('player12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player12', to='form_app.player')),
                ('player13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player13', to='form_app.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='form_app.player')),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='form_app.player')),
                ('player4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='form_app.player')),
                ('player5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='form_app.player')),
                ('player6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player6', to='form_app.player')),
                ('player7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player7', to='form_app.player')),
                ('player8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player8', to='form_app.player')),
                ('player9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player9', to='form_app.player')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner', to='form_app.player')),
                ('runner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner2', to='form_app.player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='form_app.player')),
            ],
        ),
    ]
