# Generated by Django 2.2 on 2019-05-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0006_owner_model_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_model',
            name='sport',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
