# Generated by Django 2.2 on 2019-05-31 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0007_owner_model_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_model',
            name='playerb1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb1', to='form_app.player'),
        ),
        migrations.AddField(
            model_name='owner_model',
            name='playerb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb10', to='form_app.player'),
        ),
        migrations.AddField(
            model_name='owner_model',
            name='playerb11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb11', to='form_app.player'),
        ),
        migrations.AddField(
            model_name='owner_model',
            name='playerb12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb12', to='form_app.player'),
        ),
        migrations.AddField(
            model_name='owner_model',
            name='playerb13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb13', to='form_app.player'),
        ),
        migrations.AddField(
            model_name='owner_model',
            name='playerb2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb2', to='form_app.player'),
        ),
        migrations.AddField(
            model_name='owner_model',
            name='playerb3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb3', to='form_app.player'),
        ),
        migrations.AddField(
            model_name='owner_model',
            name='playerb4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb4', to='form_app.player'),
        ),
        migrations.AddField(
            model_name='owner_model',
            name='playerb5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb5', to='form_app.player'),
        ),
        migrations.AddField(
            model_name='owner_model',
            name='playerb6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb6', to='form_app.player'),
        ),
        migrations.AddField(
            model_name='owner_model',
            name='playerb7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb7', to='form_app.player'),
        ),
        migrations.AddField(
            model_name='owner_model',
            name='playerb8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb8', to='form_app.player'),
        ),
        migrations.AddField(
            model_name='owner_model',
            name='playerb9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerb9', to='form_app.player'),
        ),
    ]
